### ISSUE TITLE
[Assig 2] Task List

### ISSUE THREAD

**Issue by andrewflash** [andrewflash/IN4342_Embedded-Systems_Laboratory#1]
### Baseline
- [x] Modify makefile in baseline code to be able to run mcprof
- [x] Add ifdef MCPROF in canny_edge.c to easily switch between profiling in PC and compiling to ARM
- [x] Add floating point support in source code and compiler options (vfp option)
- [x] Do profiling using mcprof (PC - to see predominant functions that preferably selected to be optimized), gprof (PC and ARM), and timing info echoed from board 
- [x] Do profiling for each of the pictures (both using vfp and without). Remember, there are 3 pictures in this assignment. Use makefile to configure.
- [x] Profiling analysis
### Optimization / Profiling Result
- [x] good resource to understand basic of gaussian blur (pretty much we will be doing the optimization here)

http://www.pixelstech.net/article/1353768112-Gaussian-Blur-Algorithm
https://www.youtube.com/watch?v=C_zFhWdM4ic
### Pool Notify
- [x] Learn pool_notify application from example code
- [x] Sending and receiving pgm picture between ARM and DSP using sample code, i.e. pool_notify
  https://pixhawk.ethz.ch/tutorials/omap/dsplink_api
### DSP calculation
- [x] Implement gaussian on DSP
- [x] Floating point operation to fixed point operation conversion, good article to start:
  http://www.eetindia.co.in/ARTICLES/1998APR/PDF/EEIOL_1998APR03_EMS_TA.pdf?SOURCES=DOWNLOAD
### Neon
- [x] Learn how to implement Neon code from example (using intrinsic or maybe assembler, auto-vectorization did not affect the computation significantly) source: http://processors.wiki.ti.com/index.php/Cortex-A8
- [x] Convert the gaussian smoothing to neon instruction (manipulate sequential addition and multiplication to parallel operation)
- [x] Convert it to fixed point operation
- [x] Check for variation Q-format
- [x] Compare the result (pixel error) with baseline result
### Report
- [ ] Introduction
- [ ] Problem statement
### Integration
- [ ] pool notify + DSP + Neon (load sharing)
- [ ] Verification
### Integration
- [x] Sending rows and cols info from GPP to DSP in one NOTIFY message (Uint32)
- [x] Load sharing implementation (first try to split data into two parts)
## Week 8

deadline 3 June
